// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoCommentExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "AutoCommentExtension.5f2c262b-c249-4bc3-8de9-537f420c33ec";
        public const string Name = "AutoCommentExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Miklos BARTFAI";
        public const string Tags = "";
    }
}
