// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace AutoCommentExtension
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AutoCommentExtensionString = "f7462658-9c72-4528-9b5b-05176b4dcd53";
        public static Guid AutoCommentExtension = new Guid(AutoCommentExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AutoComment = 0x0001;
        public const int AddAll= 0x0100;
        public const int AddMissing = 0x0101;
    }
}